CREATE TYPE "state" AS ENUM (
	'pendiente_de_jugar',
	'en_progreso',
	'completado'
);

CREATE TABLE IF NOT EXISTS "users" (
	"id_users" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nickname" VARCHAR(255),
	"first_name" VARCHAR(255),
	"email" VARCHAR(255) UNIQUE,
	"password_hash" VARCHAR(255),
	"pfp" VARCHAR(255),
	"color" INTEGER,
	"tags" VARCHAR(255),
	"last_online" TIMESTAMP,
	"created_in" TIMESTAMP,
	PRIMARY KEY("id_users")
);


CREATE TABLE IF NOT EXISTS "admin" (
	"id_admin" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_users_fk" INTEGER,
	PRIMARY KEY("id_admin")
);




CREATE TABLE IF NOT EXISTS "game" (
	"id_game" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"title" VARCHAR(255),
	"description" VARCHAR(255),
	"added_by" INTEGER,
	"overall_rate" SMALLINT,
	PRIMARY KEY("id_game")
);




CREATE TABLE IF NOT EXISTS "console" (
	"id_console" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255),
	"hash" VARCHAR(255),
	"manufacter" VARCHAR(255),
	"launch_date" DATE,
	PRIMARY KEY("id_console")
);




CREATE TABLE IF NOT EXISTS "roms" (
	"id_roms" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_game_fk" INTEGER,
	"id_console_fk" INTEGER,
	"url" VARCHAR(255),
	"hash" VARCHAR(255),
	PRIMARY KEY("id_roms")
);




CREATE TABLE IF NOT EXISTS "pending_games" (
	"id_pending_games" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_game_fk" INTEGER,
	"added_in" TIMESTAMP,
	"report" VARCHAR(255),
	PRIMARY KEY("id_pending_games")
);




CREATE TABLE IF NOT EXISTS "rating" (
	"id_rating" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_game_fk" INTEGER,
	"id_users_fk" INTEGER,
	"tags" VARCHAR(255),
	"rate" SMALLINT,
	PRIMARY KEY("id_rating")
);




CREATE TABLE IF NOT EXISTS "progress" (
	"id_progress" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_users_fk" INTEGER,
	"id_game_fk" INTEGER,
	"state" STATE,
	PRIMARY KEY("id_progress")
);



ALTER TABLE "admin"
ADD FOREIGN KEY("id_users_fk") REFERENCES "users"("id_users")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "game"
ADD FOREIGN KEY("added_by") REFERENCES "users"("id_users")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "roms"
ADD FOREIGN KEY("id_console_fk") REFERENCES "console"("id_console")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "roms"
ADD FOREIGN KEY("id_game_fk") REFERENCES "game"("id_game")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pending_games"
ADD FOREIGN KEY("id_game_fk") REFERENCES "game"("id_game")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "rating"
ADD FOREIGN KEY("id_game_fk") REFERENCES "game"("id_game")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "rating"
ADD FOREIGN KEY("id_users_fk") REFERENCES "users"("id_users")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "progress"
ADD FOREIGN KEY("id_users_fk") REFERENCES "users"("id_users")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "progress"
ADD FOREIGN KEY("id_game_fk") REFERENCES "game"("id_game")
ON UPDATE NO ACTION ON DELETE NO ACTION;
