db-start-empty:
	docker run -d \
	--name postgres-api-empty \
	-e POSTGRES_USER=postgres \
	-e POSTGRES_PASSWORD=postgres \
	-e POSTGRES_DB=postgres \
	-p 5432:5432 \
	postgres:18-alpine3.22

db-start:
        docker run -d \
        --name postgres-api \
        -e POSTGRES_USER=postgres \
        -e POSTGRES_PASSWORD=postgres \
        -e POSTGRES_DB=postgres \
        -p 5432:5432 \
        -v postgres_prueba_volumen:/var/lib/postgresql/data \
        postgres:18-alpine3.22


db-stop:
	docker stop postgres-api
	docker stop postgres-api-empty

db-reset:
	docker rm -f postgres-api

run:
	node index.js

install: 
	npm install

