db-start:
	docker run -d \
	--name postgres-api \
	-e POSTGRES_USER=postgres \
	-e POSTGRES_PASSWORD=postgres \
	-e POSTGRES_DB=postgres \
	-p 5432:5432 \
	postgres:18-alpine3.22

db-stop:
	docker stop postgres-api

db-reset:
	docker rm -f postgres-api

run:
	node index.js

install: 
	npm install

