services:
  db:
    image: postgres:15-alpine
    container_name: containerCbas
    restart: always
    environment:
      POSTGRES_USER: cbas
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: baseCbas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups

volumes:
  postgres_data: